@startuml アクティビティ図

title 🍛の作り方

start

fork
    :具材を切る;
    :具材を炒める;
    fork
        :煮る;
        :カレールウを入れて煮込む;
    end fork
fork again

    :米を洗う;
    :米を炊く;

end fork

:米とカレーを皿に乗せる;
stop

@enduml