@startuml ユースケース図
left to right direction
actor 社員
actor 総務部_経理部
rectangle 勤怠管理システム{
usecase 出退勤読み取りをする
usecase 残業申請を出す
usecase 残業申請を承諾するor拒否する
usecase 出退勤状況の一覧を見る
usecase 残業報告書を提出する
usecase 残業報告書を確認する
usecase ログインする
usecase 管理者ログインする
usecase 新規登録する
usecase 管理者として新規登録する
usecase 社員検索をする
usecase 申請結果通知を送る
usecase 申請結果通知を確認する
}
社員-->出退勤読み取りをする
社員-->残業申請を出す
社員-left->残業報告書を提出する
社員-->新規登録する
社員-left->申請結果通知を確認する
総務部_経理部-->残業報告書を確認する
総務部_経理部-->残業申請を承諾するor拒否する
総務部_経理部-->管理者として新規登録する
総務部_経理部-left->出退勤状況の一覧を見る
総務部_経理部-->社員検索をする
総務部_経理部-->申請結果通知を送る
総務部_経理部-->残業申請を出す
総務部_経理部-->残業報告書を提出する
社員検索をする-.>管理者ログインする:<<include>>
申請結果通知を確認する.>ログインする:<<include>>
申請結果通知を送る-.>管理者ログインする:<<include>>
出退勤状況の一覧を見る-.>管理者ログインする:<<include>>
残業申請を出す-.>ログインする:<<include>>
残業申請を承諾するor拒否する-.>管理者ログインする:<<include>>
残業報告書を提出する-.>ログインする:<<include>>
残業報告書を確認する-.>管理者ログインする:<<include>>
@enduml