@startuml ユースケース図
left to right direction
actor 社員
actor 総務部
actor 経理部
rectangle 勤怠管理システム{
usecase 出退勤読み取りをする
usecase 残業申請を出す
usecase 残業申請を承諾する
usecase 出退勤状況の確認をする
usecase 残業報告書を提出する
usecase 残業報告書を確認する
usecase ログインする
usecase 管理者ログインする
usecase 新規登録する
usecase 管理者として新規登録する
}
社員-->出退勤読み取りをする
社員-->残業申請を出す
社員-left->残業報告書を提出する
社員-->新規登録する
総務部-->残業報告書を確認する
総務部-->残業申請を承諾する
総務部-->管理者として新規登録する
経理部-left->出退勤状況の確認をする
経理部-->残業報告書を確認する
経理部-->管理者として新規登録する
出退勤状況の確認をする-.>管理者ログインする:<<include>>
残業申請を出す-.>ログインする:<<include>>
残業申請を承諾する-.>管理者ログインする:<<include>>
残業報告書を提出する-.>ログインする:<<include>>
残業報告書を確認する-.>管理者ログインする:<<include>>
@enduml