@startuml ○○医院診察予約
[*] -right-> メニュー
メニュー ---> 予約と確認 : 予約と確認ボタン\nを押す
予約と確認 ---> メニュー : 名前か電話番号を入力してから\n取消ボタンを押す
予約と確認 -right-> あなたの順番 : 名前と電話番号を入力して、\n登録ボタンを押す
予約と確認 -right-> あなたの順番 : 名前か電話番号を入力してから\n確認ボタンを押す。
あなたの順番 -up-> メニュー : メニューボタン\nを押す
今の順番 -up-> メニュー : メニューボタン\nを押す
メニュー -down--> 今の順番 : 今の順番ボタン\nを押す
メニュー -right-> [*]
@enduml